In [1]:
import numpy as np

COPY 
.copy() allows us to copy a NumPy array into another variable in such a way that when modifying the new array the changes are not reflected in the original array.

In [3]:
#Create an array 
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# With .copy() we create a copy so as not to damage our original array
#Always working with the copy version 
arr_copy = arr.copy()
arr_copy[:] = 0
print(arr)
print(arr_copy)


[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0 0 0 0 0 0]


OPERATIONS

In [12]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# Since in this case the first position of the array is 0, it shows an error but does not stop the process.
1/arr

<ipython-input-15-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [16]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
#An important operation is point by point, here are two ways to do it:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [28]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])