In [2]:
import numpy as np

In [42]:
lst = [1,2,3,4,5,6,7,8,9]
lst[0:5]

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(lst)

In [46]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz[1:3,0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [41]:
matriz[:6]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
num = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[21,22,23],[24,25,26],[27,28,29],[30,31,32]]
num = np.array(num, dtype='float64')
num.dtype

dtype('float64')

In [92]:
num[0:1,0:2,-1]

array([[3., 6.]])

scalar = np.array(8)
scalar

hola mundo 