In [2]:
import numpy as np

In [5]:
lst = [1,3,4,5,6,7,8,9]
arr = np.array(lst)
arr

array([1, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# A matrix has different vectors or lists grouped one on top of the other, it is like an Excel table
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#the first position is the first row
matriz[0]

array([1, 2, 3])

In [8]:
# To select a single element of the array, specify the position of the element separated by commas.
# Note: The first element selects the rows, the second element the columns
matriz[0,2]

3

＊＊＊＊＊＊＊＊＊　SLICING　＊＊＊＊＊＊＊＊＊

In [10]:
# It allows us to extract various data, it has a beginning and an end.
# In this example we are extracting data from position 1 to 5.
arr[1:6]

array([3, 4, 5, 6, 7])

In [9]:
arr[1:6]

array([3, 4, 5, 6, 7])

In [12]:
#To know how many dimentions are
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [13]:
# ＊＊＊＊＊＊＊＊＊DECLARE A VECTOR
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [14]:
# ＊＊＊＊＊＊＊＊＊DECLARE A MATRIX
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [15]:
# ＊＊＊＊＊＊＊＊＊DECLARE A TENSOR
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

In [16]:
# Add or remove dimensions
# You can define the number of dimensions from the array declaration

vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [17]:
# You can expand dimensions to existing arrays with expand_dims(). Axis = 0 refers to rows, while axis = 1 refers to columns.
expand = np.expand_dims(np.array([1, 2, 3]), axis = 0)
print(expand)
expand.ndim 

[[1 2 3]]


2

In [18]:
#Remove/compress dimensions that are not being used.
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


＊＊＊＊＊＊＊＊CREATE ARRAYS FROM SCRATCH＊＊＊＊＊＊＊

In [3]:
# This NumPy method allows us to generate arrays without previously defining a list.

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# A third argument allows to define a step size

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# np.zeros() It allows us to define structures or schemes.
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# np.linspace() We can define an array with a beginning an end and how many values will it have

np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
#Create random numbers
np.random.rand()

3.7964085205954845e-05

In [12]:
#We can also generate Vectors with random function 
np.random.rand(4)

array([0.84527217, 0.63807299, 0.93947309, 0.28028455])

In [13]:
#We can also generate a Matrice with random function 
np.random.rand(4,4)

array([[1.47241133e-01, 7.01167691e-01, 3.48714729e-01, 5.42036330e-01],
       [5.03474018e-01, 6.69816864e-02, 4.11112199e-01, 5.47085847e-01],
       [5.87547164e-04, 8.27332291e-02, 5.71791882e-01, 6.14311553e-01],
       [4.37530624e-01, 1.61169549e-01, 7.73741463e-01, 2.12668693e-01]])

In [16]:
#NumPy also allows us to generate integers.
#In this case integers between 8 and 88

np.random.randint(8,88)

53

In [17]:
#                (from, till, (row,colums))
np.random.randint(1,15, (3,3))

array([[ 6,  2, 10],
       [ 4,  3, 14],
       [ 4,  6,  1]])

In [36]:
arr = np.random.randint(1,10,10)
print(arr)

matriz = arr.reshape(2,5)
print(matriz)

print(arr.max())
print(matriz.max())


[7 9 9 5 1 8 2 5 6 6]
[[7 9 9 5 1]
 [8 2 5 6 6]]
9
9



# 0	Columns
# 1	Rows


In [37]:
#The higest number in each rows 
matriz.max(1)

array([9, 8])

In [38]:
#The higest number in each colum
matriz.max(0)

array([8, 9, 9, 6, 6])

In [41]:
#if we can check where is the position of the higest element 
arr.argmax()
matriz.argmax(0)

array([1, 0, 0, 1, 1])

In [44]:
#We can also calculate the distance bewteen the higest value and the smalles 
arr.ptp()
matriz.ptp(0)

array([1, 7, 4, 1, 5])

＊＊＊＊＊＊＊＊＊ANALISIS ESTADISTICO＊＊＊＊＊＊＊＊＊

In [47]:
#Organize the numbers 
arr.sort()
arr

array([1, 2, 5, 5, 6, 6, 7, 8, 9, 9])

In [48]:
#Percentile 
np.percentile(arr,50)

6.0

In [54]:
#Mediana
# the median is the value separating the higher half from the lower half of a data 
np.median(arr)
np.median(matriz,1)

array([5., 8.])

In [50]:
# Standard Deviation
# A standard deviation (or σ) is a measure of how dispersed the data is in relation to the mean. 
# Low standard deviation means data are clustered around the mean, and high standard deviation 
# indicates data are more spread out.
np.std(arr)

2.5612496949731396

In [49]:
#Variance
# Variance tells you the degree of spread in your data set.  
np.var(arr)

6.56

In [53]:
#Average 
np.mean(arr)

5.8

＊＊＊＊＊＊＊Concatenation＊＊＊＊＊＊

In [55]:
#Two arrays can be joined
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])
np.concatenate((a,b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [58]:
#we have to reshape the dimensions before 
print(a.ndim)
print(b.ndim)

b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)

2
1


array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
#sample for the axis 1
#The transpose puts our array in the opposite direction, if the original array is (1,2), with the transpose it will be (2,1)

b.T
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

＊＊＊＊＊＊CONDITIONS＊＊＊＊＊＊

In [62]:
# The conditions allow us to make more specific queries.

arr = np.linspace(1,10,10, dtype = 'int8')
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [63]:

#Returns an array of booleans where the condition is true.
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:

#Returns the values for where the conditions are True.
arr[indices_cond] 

array([ 6,  7,  8,  9, 10], dtype=int8)

In [65]:

#multiple conditions.
arr[(arr > 5) & (arr < 9)] 

array([6, 7, 8], dtype=int8)

In [66]:
#Modify the values that meet the condition.
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)